"""MAPF through ``cuplan`` (the cuda-planning distribution), CPU and CUDA.

The CUDA arm is **optional and auto-skipped**. ``cuplan.cuda_available()`` does
not merely try to import CuPy — it runs a real kernel and checks the answer —
so a machine whose driver is wedged reports ``False`` and the harness writes
``skipped`` rows carrying the reason. A missing GPU is a documented gap in the
table, never a failed benchmark and never a silent CPU run relabelled as CUDA.

The instance is generated by :mod:`openplan_bench.mapfgen`, identical to the
one the ``pymapf`` adapter receives, which is what makes the two columns
comparable rather than merely adjacent.
"""

from __future__ import annotations

import os
from typing import Any

from ..mapfgen import random_grid_instance
from ..records import Instance, RunRecord
from .base import Adapter, RunConfig, missing
from .pymapf_adapter import grid_instances

#: Suite ``planner:`` names mapped onto cuplan solver classes.
_SOLVERS = {
    "prioritized": "PrioritizedPlanning",
    "pibt": "PIBT",
}


def cuda_usable() -> tuple[bool, str]:
    """Whether a CUDA run would actually execute on a device.

    Honours ``CUPLAN_FORCE_CPU``, which is how the CPU path is exercised on a
    machine that does have a GPU.
    """
    if os.environ.get("CUPLAN_FORCE_CPU", "") not in ("", "0", "false", "no"):
        return False, "CUPLAN_FORCE_CPU is set"
    try:
        from cuplan import cuda_available
    except Exception as exc:
        return False, f"cuplan is not importable ({type(exc).__name__}: {exc})"
    try:
        if cuda_available():
            return True, ""
    except Exception as exc:
        return False, f"CUDA probe raised {type(exc).__name__}: {exc}"
    return False, "no working CUDA device (cuplan.cuda_available() returned False)"


class CuplanAdapter(Adapter):
    name = "cuplan"
    family = "mapf"
    requires = ("cuplan",)

    def available(self) -> tuple[bool, str]:
        ok, reason = missing(self.requires)
        if ok:
            return True, ""
        # cuda-planning is not on PyPI yet, so name the git install explicitly.
        return False, (
            f"{reason}. Install with: pip install "
            "'cuda-planning @ git+https://github.com/openplan-labs/cuda-planning'"
        )

    def instances(self, spec: dict[str, Any]) -> list[Instance]:
        return grid_instances(spec)

    def configs(self, spec: dict[str, Any]) -> list[RunConfig]:
        """Lift ``backend`` out of the options and onto the configuration label.

        ``pibt`` on the CPU and ``pibt`` on a GPU are two rows in the
        leaderboard, not two samples of one. If the backend stayed buried in
        the options dict they would share a label, and the aggregation would
        take a median across both — reporting a number that describes neither.
        """
        out: list[RunConfig] = []
        for config in super().configs(spec):
            backend = str(config.options.setdefault("backend", "cpu")).lower()
            config.options["backend"] = backend
            config.variant = config.variant or backend
            out.append(config)
        return out

    def skip_reason(self, config: RunConfig) -> str:
        """Non-empty when this configuration must not be run here."""
        if str(config.options.get("backend", "cpu")).lower() != "cuda":
            return ""
        ok, reason = cuda_usable()
        return "" if ok else reason

    # ------------------------------------------------------------------
    def run(
        self,
        instance: Instance,
        config: RunConfig,
        *,
        seed: int = 0,
        timeout_s: float = 60.0,
    ) -> RunRecord:
        import cuplan

        record = self.blank(instance, config, seed=seed, timeout_s=timeout_s)
        options = dict(config.options)
        backend = str(options.pop("backend", "cpu")).lower()
        record.note = f"backend={backend}"

        try:
            class_name = _SOLVERS[config.planner]
        except KeyError as error:
            raise ValueError(
                f"Unknown cuplan solver {config.planner!r}. "
                f"Available: {', '.join(sorted(_SOLVERS))}"
            ) from error

        spec = random_grid_instance(seed=seed, **instance.payload)
        pairs = zip(spec["starts"], spec["goals"], strict=True)
        problem = cuplan.Problem(
            grid=cuplan.Grid(spec["occupancy"]),
            agents=[
                cuplan.Agent(f"a{i}", tuple(start), tuple(goal))
                for i, (start, goal) in enumerate(pairs)
            ],
        )
        solver = getattr(cuplan, class_name)(backend=backend, **options)

        elapsed = self.timer()
        solution = solver.solve(problem)
        record.wall_time_s = elapsed()

        if solution is None:
            record.outcome = "unsolved"
            record.note += "; solver returned no solution"
            return record

        record.outcome = "solved"
        record.solved = True
        record.valid = bool(solution.is_valid())
        record.sum_of_costs = solution.sum_of_costs
        record.cost = float(solution.sum_of_costs)
        record.makespan = solution.makespan
        if not record.valid:
            record.note += "; returned paths contain a conflict"
        return record
